name: daybook
description: Test project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.0.0
  google_fonts: ^3.0.1
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  notes_repository:
    path: packages/notes_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/cats/
